apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-watcher-deployment
  namespace: prod
  labels:
    app: btc-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc-watcher
  template:
    metadata:
      labels:
        app: btc-watcher
    spec:
      containers:
        - name: btc-watcher
          image: 561254188060.dkr.ecr.us-west-2.amazonaws.com/btc_watcher:latest
          env:
            - name: PORT
              value: "4001"
            - name: API_URL
              value: "https://api.chainspark.io/api/transactions"
